<?php
include 'common.php';
use function Movie\Db\viewpost;
viewpost($pdo);


$stmt = $db->prepare('SELECT postID, postTitle, postCont, postDate FROM blog_posts WHERE postID = :postID');
$stmt->execute(array(':postID' => $_GET['id']));
$row = $stmt->fetch();

if($row['postID'] == ''){
    header('Location: ./');
    exit;
}

echo '<div>';
    echo '<h1>'.$row['Miss Sloane'].'</h1>';
    echo '<p>Posted on '.date('jS M Y', strtotime($row['postDate'])).'</p>';
    echo '<p>'.$row['pAfter what feels like five minutes after watching Jessica Chastain in The Zookeeper’s Wife, here I am returned to the same theatre to see her in another release. Pulling an Amy Adams of her very own (both Nocturnal Animals and Arrival came out in quick succession), I wasn’t too mad about it, as I have recently redkindled a love for Chastain that has laid dormant since the likes of The Help and A Most Violent Year. Miss Sloane promised to give me a very different performance from the quaint melodrama of The Zookeeper’s Wife, and I was excited to see what the picture had in store.
The film tells the story of a Elizabeth Sloane (Jessica Chastain), a cutthroat lobbyist in Washington D.C. who leaves her job with an established firm to fight a pro-gun bill with a smaller organisation. With a moral compass that swings more than the sixties, Miss Sloane brings a back of ethically debatable tricks with her in the fight to attain the right amount of senators, but in her controversial career move, she also leaves a team of disgruntled ex-colleagues who set out to destroy but her career and her life. The narrative, for want of a better description, feels like a combination of The Newsroom and the The West Wingon steroids, and being a huge fan of both those shows, it’s safe to say that I lapped up every single exaggerated second. Miss Sloane weaves a tale of political plotting, tricking and backstabbing that seems oddly poignant in today’s current climate, no matter how farfetched some of the details might be, and when I say farfetched, I’m talking remote controllable cockroaches with microphones. I have no doubt that a person better versed in the everyday goings on of Washington D.C. lobbying might have some more critical things to say about the credibility of unfolding events, but from a purely entertainment based viewpoint, the intrigue is delicious, the plot twists are well executed and the stakes
remain high throughout, making for a tense and satisfying two hours of highly stylised political drama.
It is both refreshing and exciting to see a fast paced, heightened yet intelligent political drama like this being fronted by a strong woman and filled with further strong supporting female performances. Though the titular Miss Sloane is far from a traditional heroine, or even an archetypal anti-hero, there is just something about the strong feminine presences combined with the masculine feel of the political environment that makes for truly captivating and enthralling tension and drama, from my personal female viewer perspective, at least. The film does a great job of sticking firmly to its cat and mouse political agenda whilst at the same time bringing in additional themes such as addiction, sexuality, mental health, many different aspects of a character that can often by judged differently depending on gender. Ultimately, if you love the engaging politics of The West Wing and the character connections and sharp wit of The Newsroom, then Miss Sloane is going to go down a real treat.'].'</p>';                
echo '</div>';

echo '<div>';
    echo '<h1>'.$row['Their finest'].'</h1>';
    echo '<p>Posted on '.date('jS M Y', strtotime($row['postDate'])).'</p>';
    echo '<p>'.$row['With films like Dunkirk, Churchill and The Zookeeper’s Wife all having been released or soon to be released, it seems like ’tis the season to be a Second World War picture. Getting in on the action too is Their Finest, a film that unlike Dunkirk or Churchill, attempts to give the audience an insight in to a part of the war that has not seen as much of the limelight in film and television over the years.
Their Finest tells the story of Catrin Cole (Gemma Arterton), a Welsh woman living in London who begins scriptwriting work for the film department of Ministry of Information, producing ‘women’s dialogue’ for moral boosting shorts. Her talent soon recognised, Catrin is asked to join a team of filmmakers making a feature film about a pair of twin sisters taking part in the evacuation of Dunkirk. Accompanied by an ageing star named Ambrose Hilliard (Bill Nighy) and a cocky, mischievous co-writer named Tom Buckley (Sam Claflin), Catrin faces degrees of sexism and adversity before she really given a chance to shine. In truth, Their Finest feels very much like a six part television drama that has been awkwardly crammed in to one two hour film. Whilst telling the central story of a ‘film within a film’, the picture also details Catrin’s marital troubles and her blossoming relationship with the confident Buckley, along with a significant focus on Ambrose Hilliard and his coming to terms with the fact that he is no longer leading man material. In trying to tell so much story in so little time, the narrative feels slightly muddy and lacks a really sharp focal point, at times even sacrificing time on the core film project in favour of Catrin’s romantic life, something that feels like a thematic misstep to me.
In fact, for a film marketed as something that celebrates the unseen achievements of a woman during WWII, there is a distinct lack of meaningful female characters in the picture. Besides protagonist Catrin and a suit wearing, caricatured lesbian ministry worker played by Rachael Stirling, the majority of the featured cast are male, with both Buckley and Hilliard taking centre stage for significant portions of the film. Take a recent picture like Hidden Figures, similarly a period piece highlighting the roles of women in seemingly unusual positions. That film is and was a perfect example of telling a story about female achievement that only briefly hints at romance in order to preserve the integrity of professional pursuits. Unfortunately, Their Finest chooses to highlight Catrin’s romantic life (albeit with one or two twists) over her professional life at nearly every opportunity, which whilst still making it a perfectly pleasing romantic period drama, stops it from becoming something that could really have been another fine example of British filmmaking that celebrates the strength of women (see Calendar Girlsor Made In Dagenham). I think what I’m trying to say is that Their Finest isn’t a bad film at all, it just isn’t the film that I wanted it to be.'].'</p>';                
echo '</div>';

echo '<div>';
    echo '<h1>'.$row['Guardians of the Galaxy'].'</h1>';
    echo '<p>Posted on '.date('jS M Y', strtotime($row['postDate'])).'</p>';
    echo '<p>'.$row['
Over time I have come to realise that I like my fantasy/science-fiction in two distinct forms, either the tense grittiness of something like the Alien franchise bordering on horror, or the more fun, joke filled space romps that you get from the likes of Star Wars, Galaxy Quest and The Fifth Element. Much to my delight, Guardians Of The Galaxy satisfied my love of the latter back in 2014, and I can’t quite believe it has already been three years since its release. As the closing titles of the film promised us, Guardians Of The Galaxy has returned, would Vol. 2 be able to capture hearts the way it did the first time around?
On the whole, I’m happy to say that yes, it absolutely did. Before I get in to the minutia and try to nitpick for fairness’ sake, let me be clear that Guardians Of The Galaxy Vol. 2 is some of the most colourful, humorous, nostalgic fun you will have in the cinema all year. The film picks up a short while after the original left us, with the newly appointed Guardians of the Galaxy, Peter Quill (Chris Pratt), Gamora (Zoe Saldana), Drax (Dave Bautista), Rocket (Bradley Cooper) and the crushingly cute Baby Groot (Vin Diesel) travelling the universe and completing jobs for hire. Of course, events very quickly turn, both when Rocket steals from the civilisation who hired them and when a figure named Ego (Kurt Russell) appears claiming to be Peter’s mysterious father. The narrative plays out in a semi Return Of The Jedi type fashion, with Peter and Ego bonding over their newfound connection whilst the rest of the crew deal with various factors that come together to create a blockbuster ending with possibly world ending ramifications. In an attempt to preserve the effective formula of the first movie, it would be fair to say that the filmmaker’s ambitions to crowd please are a little more transparent this time. What did the audience love three years ago? Groot? Okay you can have much more Groot. Drax’s lack of tact and inability to understand jokes? Okay you have much more of that too. Whilst this is by no means a bad thing, as I was certainly one such viewer who lapped these elements up in the Vol. 1, the level of pandering to the audience almost feels like a greatest hits tour rather than something completely organic. That being said, I loved every second of Baby Groot’s antics, Drax’s awkwardly forward remarks and other familiar hits like the new retro soundtrack.'].'</p>';                
echo '</div>';

echo '<div>';
    echo '<h1>'.$row['The Zookeeper's wife'].'</h1>';
    echo '<p>Posted on '.date('jS M Y', strtotime($row['postDate'])).'</p>';
    echo '<p>'.$row['Even after more than 75 years since the end of the conflict, I think it’s safe to say that the world of cinema will never run out of stories to tell about the Second World War. From battle field narratives to Holocaust narratives and everything in between, the world changing period has provided the backdrop for some of the most significant and affecting pictures ever made. Though movies of this period aren’t usually something that I seek out, The Zookeeper’s Wife had an intriguing premise that differed from the usual World War Two affair.
Based on a novel by Diane Ackerman, The Zookeeper’s Wife tells the true life tale of Antonina Zabinska (Jessica Chastain) and Jan Zabinski (Johan Heldenbergh), a Polish married couple who braved the wrath of the Nazi regime by hiding hundreds of Jews in their zoo across the war years. The opening sequence is a rather delightful one, following Antonina through the zoo as she displays her uncanny connection with all the animals in her care, establishing her character as one full of empathy and the power to help. However, the tone quickly shifts as the shadow of war looms large, and from light brevity, the film firmly finds its groove as a straight drama with the sucker punch of a devastating zoo destruction scene to prove it. Those who know me know that I absolutely cannot handle watching animals, either real or fictional, being hurt on screen, and an extended bombing sequence that features the deaths of animals in cages almost proves too much, both for the reality of that image and the wider metaphorical implications that  such a thing symbolises.
The first twenty minutes or so of The Zookeeper’s Wife are distressing from a purely visual standpoint, and although much of the ‘traditional’ upsetting imagery from this kind of narrative is interspersed and sporadically effective throughout, unfortunately the majority of the picture never quite makes the grade. In trying to tell such an epic, distance spanning story in a relatively short space of time, there is little room for character development outside of the protagonist. The Jewish people that are rescued and housed by the Zabinskis should be some of the most important characters in the story, but they are overshadowed by a misguided romantic obsession plot between Antonina and a German zoologist (Daniel Bruhl) working for Hitler that feels straight out of a melodramatic novel.
The thing is, stories like this, anything to do with the persecution of the Jewish people during the Second World War, are always going to inspire a level of emotion from an audience. Combine that with a remarkable story of human bravery in a unique setting and you get a solid, emotionally satisfying film. What must be remembered is that a film doesn’t necessarily have to be excellent to gain an emotional response, and in The Zookeepers Wife you have a perfect example of a solidly made, 6 out of 10 picture that does that what it says on the tin. Is it a future classic of the sub-genre? No. It is a perfectly acceptable way to spend two hours? Sure.'].'</p>';                
echo '</div>';
