<form action="" method="post">

    <p><label for="username">Username</label><br />
    <input name="username" type="text" value='<?php if(isset($error)){ echo $_POST['username'];}?>'></p>

    <p><label for="password">Password</label><br />
    <input name="password" type="password" value='<?php if(isset($error)){ echo $_POST['password'];}?>'></p>

    <p><label for="passwordConfirm">Confirm Password</label><br />
    <input name="password" type="passwordConfirm" value='<?php if(isset($error)){ echo $_POST['passwordConfirm'];}?>'></p>

    <p><label for="email">Email</label><br />
    <input name="email" type="text" value='<?php if(isset($error)){ echo $_POST['email'];}?>'></p>
    
    <p><input type="submit" name="submit" value='Add User'></p>

</form>

