<form action="" method="post">

    <p><label>Title</label><br />
        <input type="text" name="postTitle" /></p>

    <p><label>Description</label><br />
        <textarea name="postDesc" cols="60" rows="10" /></textarea><</p>

    <p><label>Content</label><br />
        <textarea name="postCont" cols="60" rows="10" /></textarea></p>

    <p><input type="submit" name="submit" value="Submit"></p>

</form>

