<form action="" method="post">

    <p><label for="username">Username</label><br />
        <input name="username" type="text" /></p>

    <p><label for="password">Password</label><br />
        <input name="password" type="password" /></p>

    <p><label for="passwordConfirm">Confirm Password</label><br />
        <input name="password" type="passwordConfirm" /></p>

    <p><label for="email">Email</label><br />
        <input name="email" type="text" /></p>

    <p><input type="submit" name="submit" value='Add User'></p>

</form>

